Vagrant.configure("2") do |pakito|
    pakito.vm.box = "ubuntu/bionic64"
    pakito.vm.box_version = "v20191014.0.0"
    pakito.vm.hostname = "development"

    pakito.vm.provider "virtualbox" do |vb|
        vb.gui = true
        vb.name = "development"
        vb.memory = "1024"
        vb.cpus = 1

        vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
    end

    pakito.vm.provision "ansible_local" do |ansible|
      ansible.compatibility_mode = "2.0"
      ansible.playbook = "playbook-install-docker.yml"
    end
end