---
- hosts: linuxmachines
  become: true
  tasks:
    - name: Install lvm2
      yum:
        name: lvm2
        state: latest
    - name: Install device mapper
      yum:
        name: device-mapper-persistent-data
        state: latest
    - name: Install yum utils
      yum:
        name: yum-utils
        state: latest
    - name: Add Docker Repository
      yum_repository:
        name: docker
        description: Repository for Docker CE
        baseurl: 'https://download.docker.com/linux/centos/7/$basearch/stable'
        gpgcheck: true
        gpgkey: https://download.docker.com/linux/centos/gpg
        enabled: yes
    - name: Install Docker Engine
      yum:
        name: docker-ce
        state: latest
    - name: Start and enable Docker
      service:
        name: docker
        state: started
        enabled: true